name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  webassembly:
    name: WebAssembly
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_TEST_THREADS: 32
    defaults:
      run:
        working-directory: wasm
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Tests
      run: ./rs-test.sh

  nextjs:
    name: NextJS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./wasm/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build WebAssembly
      run: npm run build:wasm
    - name: Build NextJS application
      run: npm run build
